### ISSUE TITLE
predictor's config_pb2 module not found

### ISSUE THREAD

**Issue by kristofgiber** [tensorflow/lingvo#129]
We are running the inference example provided in Introduction for lingvo on our server but without jupyter notebook. While all lingvo modules import fine and trainer runs okay, scripts relying on predictor fail with 'cannot import name predictor' error. Upon inspecting predictor itself, it shwos unresolved module reference for the `from tensorflow.core.protobuf import config_pb2` line. We tried bazel build -c opt //lingvo/core:predictor --config=cuda but the module import still fails. Which lingvo library are we supposed to compile to get predictor work?

**Comment by kristofgiber** [comment]
Why was this closed?

**Comment by jonathanasdf** [comment]
Fix was pushed in 579fa40aeb47594287e66d580ca9ec6fb4a35eb5. Seems the bot doesn't post a comment about that :/

**Comment by kristofgiber** [comment]
I've updatedand predictor's import lines are ok now but I still get 'ImportError: cannot import name predictor' when trying to run from lingvo.core import predictor. What build command am I supposed to run for this to work?

**Comment by jonathanasdf** [comment]
Check that whichever binary you build and run has predictor in its deps

**Comment by kristofgiber** [comment]
After building a binary with predictor in deps (eg. ipython_kernel) we got rid of the import error but the model inference code of script still fails, now with the error "absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_params_override before flags were parsed."
which is triggered by model_registry.

Using checkpoint /tmp/punctuator/train/ckpt-00001448
E0723 12:50:26.152736 140272753321728 _flagvalues.py:490] Trying to access flag --model_params_override before flags were parsed.
Traceback (most recent call last):
  File "/home/kristofgiber/pycharm_uploads/gcloud/gcloud_vm_gpu/lingvo_punctuator_inference.py", line 38, in <module>
    params = model_registry.GetParams('punctuator.codelab.RNMTModel', 'Test')
  File "/home/kristofgiber/lingvo/bazel-out/k8-py3-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/model_registry.py", line 223, in GetParams
    _MaybeUpdateParamsFromFlags(cfg)
  File "/home/kristofgiber/lingvo/bazel-out/k8-py3-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/model_registry.py", line 52, in _MaybeUpdateParamsFromFlags
    if FLAGS.model_params_override and FLAGS.model_params_file_override:
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 491, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_params_override before flags were parsed.
